name: Test Build

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
          scope: "@apiscp"
      - run: yarn install
      - run: yarn demo-build
